### ISSUE TITLE
Unable to savetocassandra

### ISSUE THREAD

**Issue by bigbansal** [datastax/spark-cassandra-connector#1061]
Hello,

I have Scala 2.11.8 and latest sparak-cassandra-connector and Spark2.0.2

While saving to cassandra I facing..NoClassDefFound for Logging.

scala> val collection = sc.parallelize(Seq(("cat", 30), ("fox", 40)))
collection: org.apache.spark.rdd.RDD[(String, Int)] = ParallelCollectionRDD[3] at parallelize at <console>:43

scala> collection.saveToCassandra("test", "words", SomeColumns("word", "count"))
java.lang.NoClassDefFoundError: org/apache/spark/Logging
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at com.datastax.spark.connector.util.ConfigCheck$.<init>(ConfigCheck.scala:26)
  at com.datastax.spark.connector.util.ConfigCheck$.<clinit>(ConfigCheck.scala)
  at com.datastax.spark.connector.writer.WriteConf$.fromSparkConf(WriteConf.scala:166)
  at com.datastax.spark.connector.RDDFunctions.saveToCassandra$default$4(RDDFunctions.scala:31)
  ... 58 elided
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Logging
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 74 mor

**Comment by bigbansal** [comment]
Closing. As it was reffering to old cassandra jar not 2..0.0 M3
