### ISSUE TITLE
NoClassDefFoundError: scala/collection/GenTraversableOnce$class

### ISSUE THREAD

**Issue by qiaojialingithub** [datastax/spark-cassandra-connector#1065]
I am using maven building scala.
The connector repository is
`
<dependency>

    <groupId>com.datastax.spark</groupId>

    <artifactId>spark-cassandra-connector_2.10</artifactId>

    <version>2.0.0-M1</version>

</dependency>
`

My scala version is 2.11.8.

Spark and SparkSQL version is 
`
            <dependency>

            <groupId>org.apache.spark</groupId>

            <artifactId>spark-core_2.11</artifactId>

            <version>2.0.0</version>

        </dependency>

        <dependency>

            <groupId>org.apache.spark</groupId>

            <artifactId>spark-sql_2.11</artifactId>

            <version>2.0.0</version>

        </dependency>`

My code is 
`var sc:SparkContext= null

    val conf = new SparkConf().setAppName("Cassandra Demo").setMaster("local")
      .set("spark.cassandra.connection.host", "127.0.0.1")

    sc=new SparkContext(conf)

    val rdd = sc.cassandraTable("space", "user")

    print(rdd.count())`

I got the error
`java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at com.datastax.spark.connector.util.CountingIterator.<init>(CountingIterator.scala:4)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:336)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more`

Is this because the version not match?what i should do?

**Comment by RussellSpitzer** [comment]
Yes you are using Scala 2.10 for the connector and 2.11 for spark. Switch the connector to 2.11

**Comment by qiaojialingithub** [comment]
ok Thanks a lot
