### ISSUE TITLE
java.util.NoSuchElementException with collection indexes or case-sensitive column names in index

### ISSUE THREAD

**Issue by o-kasian** [datastax/spark-cassandra-connector#1082]
Seems like connector considers `com.datastax.driver.core.IndexMetadata#target` as a column name used in index, which is false in some cases.

In a ticket discussion https://issues.apache.org/jira/browse/CASSANDRA-10216 , we can see that there are more cases like values(myCollection) or values("myCollection").
 
```
Exception in thread "main" java.util.NoSuchElementException: Column values("entity_Ids") not found in ksp.tblnm
	at com.datastax.spark.connector.cql.StructDef$$anonfun$columnByName$2.apply(Schema.scala:60)
	at com.datastax.spark.connector.cql.StructDef$$anonfun$columnByName$2.apply(Schema.scala:60)
	at scala.collection.Map$WithDefault.default(Map.scala:52)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at com.datastax.spark.connector.cql.TableDef$$anonfun$9.apply(Schema.scala:153)
```

**Comment by RussellSpitzer** [comment]
#546
