### ISSUE TITLE
scala.ScalaReflectionException: <none> is not a term

### ISSUE THREAD

**Issue by colinbreame** [datastax/spark-cassandra-connector#1088]
Using version 2.0.0-M3 of spark-cassandra-connector.

I have a programme that looks like this:

```
    var config = new SparkConf()
      .setMaster("local[4]")
      .setAppName("SparkAggregator")
      .set("spark.cassandra.connection.host", "localhost")
    var sc = new SparkContext(config)
    var file = sc.hadoopFile(....)   
    
    val spark = SparkSession.builder().getOrCreate()
    import spark.implicits._

    file.toDF.createOrReplaceTempView("things")
    var query = spark.sql("SELECT * FROM things")

   query.rdd.saveToCassandra("test", "things")
```

But it produces the following exception:

```
[error] (run-main-0) scala.ScalaReflectionException: <none> is not a term
scala.ScalaReflectionException: <none> is not a term
        at scala.reflect.api.Symbols$SymbolApi$class.asTerm(Symbols.scala:199)
        at scala.reflect.internal.Symbols$SymbolContextApiImpl.asTerm(Symbols.scala:84)
        at com.datastax.spark.connector.util.Reflect$.methodSymbol(Reflect.scala:12)
        at com.datastax.spark.connector.util.ReflectionUtil$.constructorParams(ReflectionUtil.scala:63)
        at com.datastax.spark.connector.mapper.DefaultColumnMapper.<init>(DefaultColumnMapper.scala:45)
        at com.datastax.spark.connector.mapper.LowPriorityColumnMapper$class.defaultColumnMapper(ColumnMapper.scala:47)
        at com.datastax.spark.connector.mapper.ColumnMapper$.defaultColumnMapper(ColumnMapper.scala:51)
        at XXXX.MainGrouped$.main(MainSql.scala:84)
        at XXXX.MainGrouped.main(MainSql.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by davidnadeau** [comment]
This is related to this jira ticket: https://datastax-oss.atlassian.net/browse/SPARKC-475

The problem is there is no implicit write for RDD[Row] currently. You need to map your RDD[Row] to something which has an implicit, like Array[Any], or Tuple.

Like so:

`dataFrame.rdd
  .map(row => (row.get(0), row.get(1), ...))
  .saveToCassandra(keyspaceName, tableName,`

Check out: https://github.com/datastax/spark-cassandra-connector/blob/master/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/writer/SqlRowWriter.scala
for a more elegant solution using SqlRowWrite.readColumnValues.

**Comment by RussellSpitzer** [comment]
#546

**Comment by abckaspersky** [comment]
what should I do in pyspark ?

**Comment by zhao258147** [comment]
Thanks @davidnadeau 
took me way too long to understand whats going on.

**Comment by ravindra031** [comment]
scala.ScalaReflectionException: <none> is not a method
App > 	at scala.reflect.api.Symbols$SymbolApi$class.asMethod(Symbols.scala:228)
App > 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:84)
App > 	at com.oracle.odc.utils.genericUtil$.callMethod(genericUtil.scala:60)
App > 	at com.oracle.odc.services.IdsTestScheduler.processGraphData(IdsTestScheduler.scala:28)
App > 	at com.oracle.odc.services.IdsTestScheduler.run(IdsTestScheduler.scala:21)
App > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
App > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
App > 	at java.lang.Thread.run(Thread.java:745)

**Comment by ravindra031** [comment]
what could be the error
