### ISSUE TITLE
Base64

### ISSUE THREAD

**Issue by AintMeBabe** [datastax/spark-cassandra-connector#1095]
I have problems using this class whenn calling:
`Session session = connector.openSession()`
` session.execute("MY CQL");`

```
java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
	at com.datastax.spark.connector.cql.CassandraConnectorConf.serializedConfString$lzycompute(CassandraConnectorConf.scala:40)
	at com.datastax.spark.connector.cql.CassandraConnectorConf.serializedConfString(CassandraConnectorConf.scala:34)
	at com.datastax.spark.connector.cql.CassandraConnectorConf.hashCode(CassandraConnectorConf.scala:43)
	at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
	at scala.collection.concurrent.TrieMap$MangledHashing.hash(TrieMap.scala:955)
	at scala.collection.concurrent.TrieMap.computeHash(TrieMap.scala:827)
	at scala.collection.concurrent.TrieMap.get(TrieMap.scala:842)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:50)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
```

**Comment by agcorrea** [comment]
Hello @AintMeBabe, it seems to be a dependency conflict.
I had the same problem in my project and I resolved (workaround) overriding the commons-codec version. The project is using maven and Java 8.

```xml
<dependency>
    <groupId>commons-codec</groupId>
    <artifactId>commons-codec</artifactId>
    <version>1.10</version>
</dependency>
```

**Comment by RussellSpitzer** [comment]
Please use the Jira if this persists, it does look like apache commons isn't on your classpath or some other conflict.
