### ISSUE TITLE
PySpark - Writing in Cassandra table doesn't work

### ISSUE THREAD

**Issue by steven1909** [datastax/spark-cassandra-connector#1117]
Hi,

Thank you for your help.

I have : 
 - Spark : 2.1.1
 - Scala : 2.11.8
 - Cassandra : (cqlsh --version) 5.0.1
 - Cassandra Driver : cassandra-driver-core-3.0.2.jar
 - Spark-cassandra-connector : spark-cassandra-connector-2.0.1-s_2.11.jar  (from https://spark-packages.org/package/datastax/spark-cassandra-connector)

I can easily read data from Cassandra cluster, but when i want to write data in a table i have an error. This is my code : 

## This part of code works (i can read data)
from pyspark import SparkContext, SparkConf, SQLContext, HiveContext

conf=SparkConf().setAppName('appName').setMaster('local').set("spark.cassandra.connection.host","XX.XX.XX.XX")
sc=SparkContext(conf=conf)
sqlContext = HiveContext(sc)

testDF = sqlContext.read.format("org.apache.spark.sql.cassandra").options(table="events", keyspace="system_traces").load()
testDF.count()
testDF.cache()

testDF.createOrReplaceTempView("test")
testDF.show()

result = sqlContext.sql("SELECT * FROM test WHERE source_elapsed > 1000 ").cache()
result.show()

## The 2 second line of code generate the error message below : 
testDF = sc.parallelize(range(2)).map(lambda i: (i, i,i)).toDF(['key', 'v1','v2'])
testDF.write.format("org.apache.spark.sql.cassandra").mode('append').options(table="mytable", keyspace="ks_dev1").save()

## HERE the structure of the table : 

CREATE KEYSPACE ks_dev1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks_dev1.mytable (
    key int PRIMARY KEY,
    v1 int,
    v2 int
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-19-9edee9e83de4> in <module>()
----> 1 testDF.write.format("org.apache.spark.sql.cassandra").mode('append').options(table="mytable", keyspace="ks_dev1_lake_score").save()

/users/shellec/divers/spark-2.1.1-bin-hadoop2.7/python/pyspark/sql/readwriter.pyc in save(self, path, format, mode, partitionBy, **options)
    546             self.format(format)
    547         if path is None:
--> 548             self._jwrite.save()
    549         else:
    550             self._jwrite.save(path)

/users/shellec/divers/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/users/shellec/divers/spark-2.1.1-bin-hadoop2.7/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/users/shellec/divers/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o163.save.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 9.0 failed 1 times, most recent failure: Lost task 0.0 in stage 9.0 (TID 15, localhost, executor driver): java.lang.NoClassDefFoundError: com/twitter/jsr166e/LongAdder
	at org.apache.spark.metrics.OutputMetricsUpdater$TaskMetricsSupport$class.$init$(OutputMetricsUpdater.scala:107)
	at org.apache.spark.metrics.OutputMetricsUpdater$TaskMetricsUpdater.<init>(OutputMetricsUpdater.scala:152)
	at org.apache.spark.metrics.OutputMetricsUpdater$.apply(OutputMetricsUpdater.scala:75)
	at com.datastax.spark.connector.writer.TableWriter.writeInternal(TableWriter.scala:174)
	at com.datastax.spark.connector.writer.TableWriter.insert(TableWriter.scala:162)
	at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:149)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at com.datastax.spark.connector.RDDFunctions$$anonfun$saveToCassandra$1.apply(RDDFunctions.scala:36)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)

**Comment by RussellSpitzer** [comment]
Please use Jira for bugs and The datastax academy slack channel for general help or advice
