### ISSUE TITLE
Unable to run spark scala 

### ISSUE THREAD

**Issue by gokulanathgr** [datastax/spark-cassandra-connector#1174]
Hi Team,

 I'm trying to load the data from spark to cassandra by using spark-cassandra-connector-2.0.0-s_2.11.jar. when i m trying to run the program in yarn cluster, spark is failing with error as shown in below.

Exception in thread "main" java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.cassandra. Please find packages at http://spark.apache.org/third-party-projects.html
        at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:549)
        at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
        at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:470)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
        at smarthub.api.sampletest$$anonfun$main$2.apply(sampletest.scala:23)
        at smarthub.api.sampletest$$anonfun$main$2.apply(sampletest.scala:19)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at smarthub.api.sampletest$.main(sampletest.scala:19)
        at smarthub.api.sampletest.main(sampletest.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.cassandra.DefaultSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21$$anonfun$apply$12.apply(DataSource.scala:533)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21$$anonfun$apply$12.apply(DataSource.scala:533)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21.apply(DataSource.scala:533)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$21.apply(DataSource.scala:533)
        at scala.util.Try.orElse(Try.scala:84)
        at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:533)

But i'm able to connect the cassandra cluster through spark-shell. I'm not sure where i'm making mistake. appreciate if you guys can help on this. 

**Yarn-Cluster command:**

 spark2-submit --master yarn --conf spark.executor.memory=20g --num-executors 20 --executor-cores 4 --driver-memory 15g --queue root.ops.solution --name cassandraload --conf spark.dynamicAllocation.enabled=false --class X.Y.sampletest /full-path/ScalaSparkSample-0.0.1-SNAPSHOT.jar --jars /full-path/spark-cassandra-connector-2.0.0-s_2.11.jar

Note, error is occurring while write method calls. 

Code:

package X.Y
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql._
import com.datastax.spark.connector._
import scala.collection.mutable.{Map}
object sampletest {
  def main(args: Array[String]){
    val spark = SparkSession
      .builder()
      .appName("LoadCassandra")
      .config("spark.cassandra.connection.host", "10.200.44.113")
      .getOrCreate()
    import spark.implicits._
    

    var Tablenames = collection.mutable.Map("footfall_by_subzone_day" -> "/user/soluser/API/working_place/footfall/20180101/day_subzone_data","footfall_by_subzone_hourly" -> "/user/soluser/API/working_place/footfall/20180101/hourly_subzone_data");
    
      for((tablename,path) <-Tablenames)
      {
        var DataSet = spark.read.parquet(path)
        println("path :"+ path +", tablename: "+tablename)
         DataSet.write.format("org.apache.spark.sql.cassandra").options(Map("table" -> tablename ,"keyspace" -> "api_insight")).mode("append").save()
        
      }

        
	  spark.stop()
  }
 
  
}

**Comment by RussellSpitzer** [comment]
By passing the --jars option after your submission jar it is being treated as an argument to your application jar and not to spark submit. We also strongly recommend using the --packages command. 

See

https://github.com/datastax/spark-cassandra-connector/blob/master/doc/0_quick_start.md#documentation

Also know that we use the Mailing List for support, and rarely check issues

See
https://github.com/datastax/spark-cassandra-connector/issues/546
