### ISSUE TITLE
Error while connecting Spark with Cassandra DB

### ISSUE THREAD

**Issue by nirmalb06** [datastax/spark-cassandra-connector#1179]
Hi,

I have installed spark and Cassandra in windows 10 and i have successfully connected Spark with my oracle DB, My task is to move data from one denormalised table from oracle to Cassandra DB.

I have connected to oracle and successfully created an RDD in spark for the table that i am going to move the data. but i can't able to connect to Cassandra DB in spark. Connection itself not established.

Can anyone help me to resolve this issue. below are the error i am getting while connecting to Cassandra Db from spark.

scala> import com.datastax.spark.connector._
import com.datastax.spark.connector._

scala> import org.apache.spark.{SparkConf, SparkContext}
import org.apache.spark.{SparkConf, SparkContext}

scala> import org.apache.spark.sql.;
import org.apache.spark.sql.

scala> import org.apache.spark.SparkContext._
import org.apache.spark.SparkContext._

scala> import org.apache.spark.sql.catalyst.expressions._
import org.apache.spark.sql.catalyst.expressions._

scala> import com.datastax.spark.connector.cql.CassandraConnector
:77: error: object cql is not a member of package com.datastax.spark.connector
import com.datastax.spark.connector.cql.CassandraConnector
^

scala> import org.apache.spark.sql.cassandra.CassandraSQLContext
:77: error: object cassandra is not a member of package org.apache.spark.sql
import org.apache.spark.sql.cassandra.CassandraSQLContext
^

scala>

scala> val sc = new SparkContext(conf)
org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
org.apache.spark.repl.Main$.createSparkSession(Main.scala:103)
(:15)
(:43)
(:45)
.(:49)
.()
.$print$lzycompute(:7)
.$print(:6)
$print()
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2449)
at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$2.apply(SparkContext.scala:2445)
at scala.Option.foreach(Option.scala:257)
at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:2445)
at org.apache.spark.SparkContext$.markPartiallyConstructed(SparkContext.scala:2534)
at org.apache.spark.SparkContext.(SparkContext.scala:84)
... 81 elided

scala> val data = sc.cassandraTable("killrvideo", "videos")
:78: error: value cassandraTable is not a member of org.apache.spark.SparkContext
val data = sc.cassandraTable("killrvideo", "videos")
^

scala> val data = spark.setCassandraConf(Map( "spark.cassandra.connection.host" -> "127.0.0.1",
| "spark.cassandra.connection.port" -> "9042"))
:77: error: value setCassandraConf is not a member of org.apache.spark.sql.SparkSession
val data = spark.setCassandraConf(Map( "spark.cassandra.connection.host" -> "127.0.0.1",
^

scala>

Do I need any JAR's like ODBC6.jar for oracle to be copied to Spark --> Jar Folder. IF so can any one provide me an Spark Cassandra connector JAR. Kindly help me to resolve this issue.

**Comment by nirmalb06** [comment]
Hi ,

I resolved the issue using the park Cassandra connector JAR. Thanks!
