### ISSUE TITLE
org.apache.spark.sql.AnalysisException - on querying a Cassandra table which has many columns

### ISSUE THREAD

**Issue by praveenpotru** [datastax/spark-cassandra-connector#1185]
### Environment
DSE - 6.0.0
spark - 2.2
Cassandra - 3.11

### Issue
org.apache.spark.sql.AnalysisException is thrown on querying Cassandra tables which has many columns. In my case, Table has 110 columns, on executing select query "select * from xxxx", following exception appeared..

org.apache.spark.sql.AnalysisException: Could not read schema from the hive metastore because it is corrupted. (missing part 1 of the schema, 2 parts are expected).;
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$29.apply(HiveExternalCatalog.scala:1203)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$29.apply(HiveExternalCatalog.scala:1200)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.hive.HiveExternalCatalog$.org$apache$spark$sql$hive$HiveExternalCatalog$$getSchemaFromTableProperties(HiveExternalCatalog.scala:1200)
	at org.apache.spark.sql.hive.HiveExternalCatalog.restoreDataSourceTable(HiveExternalCatalog.scala:781)
	at org.apache.spark.sql.hive.HiveExternalCatalog.org$apache$spark$sql$hive$HiveExternalCatalog$$restoreTableMetadata(HiveExternalCatalog.scala:683)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$getTable$1.apply(HiveExternalCatalog.scala:648)
	at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$getTable$1.apply(HiveExternalCatalog.scala:648)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:97)
	at org.apache.spark.sql.hive.HiveExternalCatalog.getTable(HiveExternalCatalog.scala:647)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.lookupRelation(SessionCatalog.scala:681)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$lookupTableFromCatalog(Analyzer.scala:640)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.resolveRelation(Analyzer.scala:595)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$8.applyOrElse(Analyzer.scala:625)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$8.applyOrElse(Analyzer.scala:618)

**Comment by RussellSpitzer** [comment]
#546
