### ISSUE TITLE
sbt assembly is throwing error for 2.3.1 

### ISSUE THREAD

**Issue by manas86** [datastax/spark-cassandra-connector#1194]
Hi All,

Can anyone help me what i'm doing wrong here, sbt assembly is giving me below error in my docker container.Any pointer to fix it, would be great. 

 fatal: Not a git repository (or any of the parent directories): .git
java.lang.RuntimeException: Nonzero exit value: 128

```
RUN curl -L -sO https://github.com/datastax/spark-cassandra-connector/archive/v2.3.1.zip
RUN unzip v2.3.1.zip ; ln -s spark-cassandra-connector-2.3.1 /spark-cassandra-connector
RUN cd /spark-cassandra-connector ; ./sbt/sbt assembly || true
```

----o/p-----
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
[info] Loading project definition from /spark-cassandra-connector-2.3.1/project
Using releases: https://oss.sonatype.org/service/local/staging/deploy/maven2 for releases
Using snapshots: https://oss.sonatype.org/content/repositories/snapshots for snapshots
fatal: Not a git repository (or any of the parent directories): .git
java.lang.RuntimeException: Nonzero exit value: 128
        at scala.sys.package$.error(package.scala:27)
        at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:134)
        at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
        at Settings$.currentVersion(Settings.scala:43)
        at Settings$$anonfun$buildSettings$2.apply(Settings.scala:47)
        at Settings$$anonfun$buildSettings$2.apply(Settings.scala:47)
        at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit value: 128
```

**Comment by bcantoni** [comment]
@manas86 we are no longer using GitHub Issues on this project. See this link for various ways to contact other community users and/or report bugs:
https://github.com/datastax/spark-cassandra-connector#community
