### ISSUE TITLE
DataFrame.show() error.

### ISSUE THREAD

**Issue by kingreatwill** [datastax/spark-cassandra-connector#1257]
table
```
CREATE KEYSPACE examples WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};

CREATE TABLE examples.sample_times (a int, b timestamp, c timeuuid, d bigint, PRIMARY KEY (a,b,c,d));
INSERT INTO examples.sample_times (a,b,c,d) VALUES (1, toUnixTimestamp(now()), 50554d6e-29bb-11e5-b345-feff819cdc9f, toTimestamp(now()));
INSERT INTO examples.sample_times (a,b,c,d) VALUES (2, toUnixTimestamp(now()), now(), toTimestamp(now()));
```
pyspark --packages com.datastax.spark:spark-cassandra-connector_2.12:2.5.0
```
def load_and_get_table_df(keys_space_name, table_name):
    table_df = spark.read\
        .format("org.apache.spark.sql.cassandra")\
        .options(table=table_name, keyspace=keys_space_name)\
        .load()
    return table_df

# sample_kvs = load_and_get_table_df("examples", "tbl_sample_kv")
sample_kvs = load_and_get_table_df("examples", "sample_times")
sample_kvs.show()
```
error
```
java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: org.apache.spark.unsafe.types.UTF8String is not a valid external type for schema of string
staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, id), StringType), true, false) AS id#10
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, value), StringType), true, false) AS value#11
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:215)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:197)
```

**Comment by jtgrabowski** [comment]
Please don't create Github issues, see #546 for details.

**Comment by kingreatwill** [comment]
--packages com.datastax.spark:spark-cassandra-connector_2.12:3.0.0-beta
