### ISSUE TITLE
spark-3.0.0 read data from cassandra failed with 3.0.0-alpha2, details as following.

### ISSUE THREAD

**Issue by bridge168** [datastax/spark-cassandra-connector#1259]
pyspark codes:
        ss_cassandra = SparkSession.builder.appName("cassandra") \
            .config('spark.cassandra.connection.host', self.host).getOrCreate()
        cassandra_df = ss_cassandra.read \
            .format("org.apache.spark.sql.cassandra").load(table=self.table, keyspace=self.keyspace)
Erros info:
Traceback (most recent call last):
  File "/usr/local/bin/run.py", line 8, in <module>
    CassandraDataAnalysis().process_data_cassandra()
  File "/usr/local/lib/python3.7/dist-packages/data_smart/data_analysis.py", line 56, in process_data_cassandra
    .format("org.apache.spark.sql.cassandra").load(table=self.table, keyspace=self.keyspace)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 131, in deco
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o124.load.
: java.lang.NoClassDefFoundError: com/datastax/spark/connector/TableRef
	at org.apache.spark.sql.cassandra.DefaultSource$.TableRefAndOptions(DefaultSource.scala:142)
	at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:56)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.datastax.spark.connector.TableRef
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 19 more

**Comment by bridge168** [comment]
pyspark 3.0.0 on kubernetes 1.18.3

**Comment by alexott** [comment]
show how do you start your application. the problem is that you don't have `spark-cassandra-connector-driver`  in your classpath. use `--packages` to force the pulling all deps by spark

**Comment by kingreatwill** [comment]
Try 3.0.0-beta.

os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.datastax.spark:spark-cassandra-connector_2.12:3.0.0-beta pyspark-shell'
