### ISSUE TITLE
AWS Keyspaces Compatibility

### ISSUE THREAD

**Issue by andrericos** [datastax/spark-cassandra-connector#1262]
Hi everyone,

Is there any plans to make this connector compatible with AWS Keyspaces?

I have tested this connector and It does not work. It seems the AWS uses a Partitioner which is not compatible.

Here is what I got:

- OS: MacOS Catalina
- Java: azul-zulu-8.46.0.19-jdk8.0.252
- Spark: 2.4.3

```scala
package spark.cassandra
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession
import org.scalatest.funsuite.AnyFunSuite

class CassandraTest extends AnyFunSuite {
    test("Acessing Amazon Keyspaces from Spark") {

        val conf = new SparkConf()
          .setAppName("SparkCassandraApp")
          .setMaster("local[*]")
          .set("spark.cassandra.connection.host", "cassandra.sa-east-1.amazonaws.com")
          .set("spark.cassandra.connection.port", "9142")

          .set("spark.cassandra.connection.ssl.enabled", "true")
          .set("spark.cassandra.connection.ssl.trustStore.path", "/tmp/cassandra_truststore.jks")
          .set("spark.cassandra.connection.ssl.trustStore.password", "changeit")
          .set("spark.cassandra.auth.username", "user-at-00000000")
          .set("spark.cassandra.auth.password", "AAAAAAAAAAAAAAAAAAAAAA")

        val sparkSession = SparkSession
          .builder()
          .config(conf)
          .getOrCreate()

        sparkSession.sparkContext.setCheckpointDir("/tmp/")

        val df = sparkSession
          .read
          .format("org.apache.spark.sql.cassandra")
          .options(Map("table" -> "tutorialtable", "keyspace" -> "tutorialkeyspace"))
          .load

        df.show(false)
        df.printSchema
        df.count
    }
}
```

Log error:

```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/07/13 15:42:21 INFO SparkContext: Running Spark version 2.4.3
20/07/13 15:42:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/07/13 15:42:22 INFO SparkContext: Submitted application: SparkCassandraApp
20/07/13 15:42:22 INFO SecurityManager: Changing view acls to: c000001
20/07/13 15:42:22 INFO SecurityManager: Changing modify acls to: c000001
20/07/13 15:42:22 INFO SecurityManager: Changing view acls groups to: 
20/07/13 15:42:22 INFO SecurityManager: Changing modify acls groups to: 
20/07/13 15:42:22 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(c000001); groups with view permissions: Set(); users  with modify permissions: Set(c000001); groups with modify permissions: Set()
20/07/13 15:42:22 INFO Utils: Successfully started service 'sparkDriver' on port 53243.
20/07/13 15:42:22 INFO SparkEnv: Registering MapOutputTracker
20/07/13 15:42:22 INFO SparkEnv: Registering BlockManagerMaster
20/07/13 15:42:22 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/07/13 15:42:22 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/07/13 15:42:22 INFO DiskBlockManager: Created local directory at /private/var/folders/f8/bqdgz2cj00g756ynk3j10n1m0000gp/T/blockmgr-34a7829a-1154-4061-a065-fc7f56253f78
20/07/13 15:42:22 INFO MemoryStore: MemoryStore started with capacity 2004.6 MB
20/07/13 15:42:22 INFO SparkEnv: Registering OutputCommitCoordinator
20/07/13 15:42:23 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/07/13 15:42:23 INFO SparkUI: Bound SparkUI to 127.0.0.1, and started at http://localhost:4040
20/07/13 15:42:23 INFO Executor: Starting executor ID driver on host localhost
20/07/13 15:42:23 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 53244.
20/07/13 15:42:23 INFO NettyBlockTransferService: Server created on localhost:53244
20/07/13 15:42:23 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/07/13 15:42:23 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, localhost, 53244, None)
20/07/13 15:42:23 INFO BlockManagerMasterEndpoint: Registering block manager localhost:53244 with 2004.6 MB RAM, BlockManagerId(driver, localhost, 53244, None)
20/07/13 15:42:23 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, localhost, 53244, None)
20/07/13 15:42:23 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, localhost, 53244, None)
20/07/13 15:42:23 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/tmp/spark-warehouse').
20/07/13 15:42:23 INFO SharedState: Warehouse path is 'file:/tmp/spark-warehouse'.
20/07/13 15:42:24 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
20/07/13 15:42:25 INFO DefaultMavenCoordinates: DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core-shaded) version 4.5.0
20/07/13 15:42:25 INFO Clock: Could not access native clock (see debug logs for details), falling back to Java system clock
20/07/13 15:42:26 INFO ChannelFactory: [s0] Failed to connect with protocol DSE_V2, retrying with DSE_V1
20/07/13 15:42:26 INFO ChannelFactory: [s0] Failed to connect with protocol DSE_V1, retrying with V4
20/07/13 15:42:26 INFO Uuids: PID obtained through native call to getpid(): 0
20/07/13 15:42:26 WARN DefaultTopologyMonitor: [s0] Control node cassandra.sa-east-1.amazonaws.com/18.230.46.137:9142 has an entry for itself in system.peers: this entry will be ignored. This is likely due to a misconfiguration; please verify your rpc_address configuration in cassandra.yaml on all nodes in your cluster.
20/07/13 15:42:26 WARN DefaultTokenFactoryRegistry: [s0] Unsupported partitioner 'com.amazonaws.cassandra.DefaultPartitioner', token map will be empty.
20/07/13 15:42:26 WARN SchemaAgreementChecker: [s0] Unknown peer 6fdc1de5-271a-3bb8-955c-b34b0a04bafe, excluding from schema agreement check
20/07/13 15:42:28 INFO CassandraConnector: Connected to Cassandra cluster.


Unsupported partitioner: com.amazonaws.cassandra.DefaultPartitioner
java.lang.IllegalArgumentException: Unsupported partitioner: com.amazonaws.cassandra.DefaultPartitioner
	at com.datastax.spark.connector.rdd.partitioner.dht.TokenFactory$.forCassandraPartitioner(TokenFactory.scala:92)
	at com.datastax.spark.connector.rdd.partitioner.dht.TokenFactory$.forSystemLocalPartitioner(TokenFactory.scala:101)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:680)
	at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:57)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
	at spark.cassandra.CassandraTest$$anonfun$1.apply$mcJ$sp(CassandraTest.scala:39)
	at spark.cassandra.CassandraTest$$anonfun$1.apply(CassandraTest.scala:9)
	at spark.cassandra.CassandraTest$$anonfun$1.apply(CassandraTest.scala:9)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike$class.invokeWithFixture$1(AnyFunSuiteLike.scala:186)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anonfun$runTest$1.apply(AnyFunSuiteLike.scala:199)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anonfun$runTest$1.apply(AnyFunSuiteLike.scala:199)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.funsuite.AnyFunSuiteLike$class.runTest(AnyFunSuiteLike.scala:199)
	at org.scalatest.funsuite.AnyFunSuite.runTest(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anonfun$runTests$1.apply(AnyFunSuiteLike.scala:232)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anonfun$runTests$1.apply(AnyFunSuiteLike.scala:232)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funsuite.AnyFunSuiteLike$class.runTests(AnyFunSuiteLike.scala:232)
	at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1562)
	at org.scalatest.Suite$class.run(Suite.scala:1112)
	at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anonfun$run$1.apply(AnyFunSuiteLike.scala:236)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anonfun$run$1.apply(AnyFunSuiteLike.scala:236)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funsuite.AnyFunSuiteLike$class.run(AnyFunSuiteLike.scala:236)
	at org.scalatest.funsuite.AnyFunSuite.run(AnyFunSuite.scala:1562)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1314)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1308)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1308)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:972)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1474)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)


20/07/13 15:42:28 INFO SparkContext: Invoking stop() from shutdown hook
20/07/13 15:42:28 INFO SparkUI: Stopped Spark web UI at http://localhost:4040
20/07/13 15:42:28 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/07/13 15:42:28 INFO MemoryStore: MemoryStore cleared
20/07/13 15:42:28 INFO BlockManager: BlockManager stopped
20/07/13 15:42:28 INFO BlockManagerMaster: BlockManagerMaster stopped
20/07/13 15:42:28 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/07/13 15:42:28 INFO SparkContext: Successfully stopped SparkContext
20/07/13 15:42:28 INFO ShutdownHookManager: Shutdown hook called
20/07/13 15:42:28 INFO ShutdownHookManager: Deleting directory /private/var/folders/f8/bqdgz2cj00g756ynk3j10n1m0000gp/T/spark-524c3e53-bc93-4347-88f5-c6383c594439
20/07/13 15:42:28 INFO CassandraConnector: Disconnected from Cassandra cluster.
20/07/13 15:42:28 INFO SerialShutdownHooks: Successfully executed shutdown hook: Clearing session cache for C* connector

Process finished with exit code 0
```

Thanks,

Best Regards,

**Comment by jtgrabowski** [comment]
Hi @andrericos we have no plans to support AWS Keyspaces. Our big next step on the road map is releasing SCC 3.0.0 compatible with Spark 3.0.0. Could you please use jira for subsequent requests? See #546 for details.
