### ISSUE TITLE
Spark Job Getting Stuck when writing to cassandra

### ISSUE THREAD

**Issue by pouryas** [datastax/spark-cassandra-connector#237]
Hey all

I am not sure if this is something that anyone has experienced before. We have 5 XLarge AWS nodes that we are running Cassandra on and I am using Spark Cassandra Connector to extract some data from S3 and insert it into Cassandra. The problem that we are seeing on various machines (Locally and on the cluster) is that sometimes our jobs get stuck at the very last stage tasks and we have to kill the job. As I was writing this I tired twice and the first time the job finished and the second time finished 839/840 tasks and got stuck at the last one. 

What could be the reason for this?

**Comment by gk45965** [comment]
Please resolve my error   =====>   when writing data to cassndra 

java.lang.NullPointerException: null
	at com.datastax.driver.core.Cluster$Manager.close(Cluster.java:1627) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.driver.core.Cluster$Manager.access$200(Cluster.java:1318) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.driver.core.Cluster.closeAsync(Cluster.java:566) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.driver.core.Cluster.close(Cluster.java:578) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:167) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:32) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.RefCountedCache.syncAcquire(RefCountedCache.scala:69) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:57) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:122) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:332) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.cql.Schema$.tableFromCassandra(Schema.scala:352) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.writer.TableWriter$.apply(TableWriter.scala:379) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.RDDFunctions.saveToCassandra(RDDFunctions.scala:35) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.japi.RDDJavaFunctions.saveToCassandra(RDDJavaFunctions.java:61) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.datastax.spark.connector.japi.RDDAndDStreamCommonJavaFunctions$WriterBuilder.saveToCassandra(RDDAndDStreamCommonJavaFunctions.java:486) ~[spark-cassandra-connector_2.11-2.3.0.jar!/:2.3.0]
	at com.gaurav.sparkstreamingwithkafkacassendranew.SparkStreamingWithKafkaCassendraNewApplication.lambda$main$b0eecefb$1(SparkStreamingWithKafkaCassendraNewApplication.java:63) ~[classes!/:0.0.1-SNAPSHOT]
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:628) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:628) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:416) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.8.jar!/:na]
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:257) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:257) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:257) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) ~[scala-library-2.11.8.jar!/:na]
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:256) ~[spark-streaming_2.11-2.3.0.jar!/:2.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]
