### ISSUE TITLE
cannot connect to cassandra cluster

### ISSUE THREAD

**Issue by liu-hongwei** [datastax/spark-cassandra-connector#311]
here is the test code in MonitorApp .scala:
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf
import com.datastax.spark.connector._
import org.apache.spark.streaming._
import org.apache.spark.streaming.StreamingContext._
import scala.collection.mutable.SynchronizedQueue
import org.apache.spark.rdd.RDD

object MonitorApp {
  def main(args: Array[String]) {

    val conf = new SparkConf()
        .setAppName("Monitor Application")
        .set("spark.cassandra.connection.host", "xxx.cloudapp.net")
        .set("spark.cassandra.auth.username", "xxx")
        .set("spark.cassandra.auth.password", "xxx")

    val sc = new SparkContext(conf)
    val cr = sc.cassandraTable[(Int,String)]("emiltest", "stuff").select("t", "v")
    println("***************************")
    val cr1 = cr.filter(_._1 < 3)
    println(cr1.count)
    cr1.foreach { println }
    println("***************************")
    val cr2 = cr.where("t > 2")
    println(cr2.count)
    cr2.foreach { println }
    println("***************************")
}
}

and submit it to spark in run.sh:

export MYSPARKLIBJARS=/home/sparkadmin/samples/MonitorApp/lib_managed/jars
spark-submit --class MonitorApp --master local[4] --jars $MYSPARKLIBJARS/org.apache.cassandra/cassandra-thrift/cassandra-thrift-2.0.9.jar,$MYSPARKLIBJARS/org.apache.thrift/libthrift/libthrift-0.9.1.jar,$MYSPARKLIBJARS/com.datastax.spark/spark-cassandra-connector_2.10/spark-cassandra-connector_2.10-1.1.0-alpha1.jar,$MYSPARKLIBJARS/com.datastax.cassandra/cassandra-driver-core/cassandra-driver-core-2.0.4.jar,$MYSPARKLIBJARS/joda-time/joda-time/joda-time-2.4.jar target/scala-2.10/monitorapp_2.10-1.0.jar

but i can not connect to the cassandra cluster:

14/10/08 00:08:55 ERROR Session: Error creating pool to /100.75.252.25:9042
com.datastax.driver.core.TransportException: [/100.75.252.25:9042] Cannot connect
        at com.datastax.driver.core.Connection.<init>(Connection.java:104)
        at com.datastax.driver.core.PooledConnection.<init>(PooledConnection.java:28)
        at com.datastax.driver.core.Connection$Factory.open(Connection.java:458)
        at com.datastax.driver.core.HostConnectionPool.<init>(HostConnectionPool.java:85)
        at com.datastax.driver.core.SessionManager.replacePool(SessionManager.java:241)
        at com.datastax.driver.core.SessionManager.access$400(SessionManager.java:42)
        at com.datastax.driver.core.SessionManager$3.call(SessionManager.java:273)
        at com.datastax.driver.core.SessionManager$3.call(SessionManager.java:265)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /100.75.252.25:9042
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:137)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        ... 3 more

what wrong am i doing here?

Thanks

**Comment by bcantoni** [comment]
Closing because it looks like this discussion has concluded.

If there are follow-up comments, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
