### ISSUE TITLE
All host(s) tried for query failed (no host was tried)

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#347]
I'm getting the issue in the title quite often. The drivers discovers my C* ring correctly and then fails this this "no host was tried".   Any idea what might cause this?

Sample exception:
```bash
14/10/17 12:47:36 INFO com.datastax.driver.core.Cluster: New Cassandra host /xxx.xxx.xxx.120:9042 added
14/10/17 12:47:36 INFO com.datastax.driver.core.Cluster: New Cassandra host /xxx.xxx.xxx.108:9042 added
14/10/17 12:47:36 INFO com.datastax.driver.core.Cluster: New Cassandra host /xxx.xxx.xxx.42:9042 added
14/10/17 12:47:36 INFO com.datastax.spark.connector.cql.CassandraConnector: Connected to Cassandra cluster: development_cassandra
14/10/17 12:47:36 INFO com.datastax.driver.core.Cluster: New Cassandra host /xxx.xxx.xxx.3:9042 added
14/10/17 12:47:36 INFO com.datastax.driver.core.Cluster: New Cassandra host /xxx.xxx.xxx.:9042 added
14/10/17 12:47:36 INFO com.datastax.driver.core.Cluster: New Cassandra host /xxx.xxx.xxx.10:9042 added
14/10/17 12:47:37 ERROR jobs.actualvalues.ActualValues: Unable to create cassandra model
jobs.common.CassandraModelCreateException: Unable to create model for: abc
	at jobs.common.CassandraModelCreator$.loop$1(CassandraModelCreator.scala:18)
	at jobs.common.CassandraModelCreator$.createModel(CassandraModelCreator.scala:21)
	at jobs.actualvalues.ActualValues$$anonfun$6.apply(ActualValues.scala:32)
	at jobs.actualvalues.ActualValues$$anonfun$6.apply(ActualValues.scala:31)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:99)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$withSessionDo$1.apply(CassandraConnector.scala:98)
	at com.datastax.spark.connector.util.IOUtils$.closeAfterUse(IOUtils.scala:16)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:98)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)
	at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:65)
	at com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:256)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:172)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36)

```

**Comment by markncooper** [comment]
Scratch that - we have code that is returning an iterator to ResultSet and seemingly reading paged data for a long period of time. During our reading the connection is getting timed out. This is an error in our usage and not a bug.
