### ISSUE TITLE
Intermittent ERROR when running it:test

### ISSUE THREAD

**Issue by pkolaczk** [datastax/spark-cassandra-connector#387]
This is in b1.1:

```
[info] TableWriterColumnNamesSpec:
[info] TableWriter
[info] - must distinguish `AllColumns` (8 milliseconds)
[info] - must distinguish and use only specified column names if provided (2 milliseconds)
[info] - must fail in the RowWriter if provided specified column names do not include primary keys (13 milliseconds)
[info] ActorStreamingSpec:
[info] actorStream
ERROR 16:32:50,886 com.datastax.driver.core.ExceptionCatchingRunnable (ExceptionCatchingRunnable.java:36) - Unexpected error while executing task
java.lang.IllegalStateException: Can't use this Cluster instance because it was previously closed
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1139)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:318)
	at com.datastax.driver.core.SessionManager.updateCreatedPools(SessionManager.java:307)
	at com.datastax.driver.core.Cluster$Manager.onAdd(Cluster.java:1626)
	at com.datastax.driver.core.Cluster$Manager.access$1100(Cluster.java:1071)
	at com.datastax.driver.core.Cluster$Manager$6.runMayThrow(Cluster.java:1542)
	at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[info] - must write from the actor stream to cassandra table: demo.streaming_wordcount (3 seconds, 808 milliseconds)
```

**Comment by jacek-lewandowski** [comment]
I suppose this is obsolete.
