### ISSUE TITLE
Api unable to run production grade load

### ISSUE THREAD

**Issue by critikaled** [datastax/spark-cassandra-connector#392]
Hi,
I'm trying to run production grade load i'm getting the following error can any body help me in fixing this.
thanks in advance.

java.io.IOException: Failed to fetch splits of TokenRange(7930318832536493312,8000341079063023682,Set(CassandraNode(/127.0.0.1,/127.0.0.1)),None) from all endpoints: CassandraNode(/127.0.0.1,/127.0.0.1)
com.datastax.spark.connector.rdd.partitioner.ServerSideTokenRangeSplitter$$anonfun$split$2.apply(ServerSideTokenRangeSplitter.scala:55)
com.datastax.spark.connector.rdd.partitioner.ServerSideTokenRangeSplitter$$anonfun$split$2.apply(ServerSideTokenRangeSplitter.scala:49)
scala.Option.getOrElse(Option.scala:120)
com.datastax.spark.connector.rdd.partitioner.ServerSideTokenRangeSplitter.split(ServerSideTokenRangeSplitter.scala:49)
com.datastax.spark.connector.rdd.partitioner.CassandraRDDPartitioner$$anonfun$com$datastax$spark$connector$rdd$partitioner$CassandraRDDPartitioner$$splitsOf$1.apply(CassandraRDDPartitioner.scala:77)
com.datastax.spark.connector.rdd.partitioner.CassandraRDDPartitioner$$anonfun$com$datastax$spark$connector$rdd$partitioner$CassandraRDDPartitioner$$splitsOf$1.apply(CassandraRDDPartitioner.scala:76)
scala.collection.parallel.mutable.ParArray$ParArrayIterator.flatmap2combiner(ParArray.scala:418)
scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1075)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
.
.
.
        scala.collection.parallel.package$$anon$1.alongWith(package.scala:85)
        scala.collection.parallel.Task$class.mergeThrowables(Tasks.scala:86)
        scala.collection.parallel.ParIterableLike$FlatMap.mergeThrowables(ParIterableLike.scala:1071)
        scala.collection.parallel.Task$class.tryMerge(Tasks.scala:72)
        scala.collection.parallel.ParIterableLike$FlatMap.tryMerge(ParIterableLike.scala:1071)
        scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:190)
        scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
        scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
        scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
        scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
        scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
        scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:444)
        scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:514)
        scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Tasks.scala:492)
        scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:64)
        scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:961)
        scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
        scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
        scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:956)
        scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
        scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
        scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1185)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1174)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1173)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1173)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:688)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1391)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[trace] Stack trace suppressed: run last compile:run for the full output.

**Comment by bcantoni** [comment]
Closing this older discussion.

If there are follow-up comments or help needed, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
