### ISSUE TITLE
spark 1.1.0 ++ connector 1.1.0 with cassandra 2.1.2  - java.lang.ClassNotFoundException: $line28.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$anonfun$1

### ISSUE THREAD

**Issue by kfleischmann** [datastax/spark-cassandra-connector#449]
Hey guys. i have cassandra 2-node cluster with an spark (stand-alone) on top of it. I have built the lastest version 1.1.0 of spark-cassandra-connector.

1. Reading the data out of cassandra rdd.toArray works
2. Writing data back to cassandra works fine as well.
3. map operations fails as described here....

any Idea? 

Using the spark console with the commands

/spark-shell --jars /home/cassandra/spark-cassandra-connector/spark-cassandra-connector/target/scala-2.10/spark-cassandra-connector-assembly-1.1.0-SNAPSHOT.jar

sc.stop
import com.datastax.spark.connector._
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf

val conf = new SparkConf(true).set("spark.cassandra.connection.host", "cassandra")
val sc = new SparkContext("spark://cassandra:7077", "test", conf)
val rdd = sc.cassandraTable("test", "kv")

WORKS
rdd.collect
println(rdd.count)
println(rdd.first)

FAILS
println(rdd.map(_.getInt("value")).sum)     

---------------------------------------

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
```
14/11/25 23:39:01 INFO CoarseGrainedExecutorBackend: Registered signal handlers for [TERM, HUP, INT]
14/11/25 23:39:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
14/11/25 23:39:03 INFO SecurityManager: Changing view acls to: cassandra
14/11/25 23:39:03 INFO SecurityManager: Changing modify acls to: cassandra
14/11/25 23:39:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(cassandra); users with modify permissions: Set(cassandra)
14/11/25 23:39:04 INFO Slf4jLogger: Slf4jLogger started
14/11/25 23:39:04 INFO Remoting: Starting remoting
14/11/25 23:39:05 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://driverPropsFetcher@cassandra:45364]
14/11/25 23:39:05 INFO Utils: Successfully started service 'driverPropsFetcher' on port 45364.
14/11/25 23:39:05 INFO SecurityManager: Changing view acls to: cassandra
14/11/25 23:39:05 INFO SecurityManager: Changing modify acls to: cassandra
14/11/25 23:39:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(cassandra); users with modify permissions: Set(cassandra)
14/11/25 23:39:05 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
14/11/25 23:39:06 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
14/11/25 23:39:06 INFO Slf4jLogger: Slf4jLogger started
14/11/25 23:39:06 INFO Remoting: Starting remoting
14/11/25 23:39:06 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
14/11/25 23:39:06 INFO Utils: Successfully started service 'sparkExecutor' on port 42123.
14/11/25 23:39:06 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkExecutor@cassandra:42123]
14/11/25 23:39:06 INFO CoarseGrainedExecutorBackend: Connecting to driver: akka.tcp://sparkDriver@cassandra:52708/user/CoarseGrainedScheduler
14/11/25 23:39:06 INFO WorkerWatcher: Connecting to worker akka.tcp://sparkWorker@cassandra:37451/user/Worker
14/11/25 23:39:06 INFO WorkerWatcher: Successfully connected to akka.tcp://sparkWorker@cassandra:37451/user/Worker
14/11/25 23:39:06 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
14/11/25 23:39:06 INFO SecurityManager: Changing view acls to: cassandra
14/11/25 23:39:06 INFO SecurityManager: Changing modify acls to: cassandra
14/11/25 23:39:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(cassandra); users with modify permissions: Set(cassandra)
14/11/25 23:39:06 INFO AkkaUtils: Connecting to MapOutputTracker: akka.tcp://sparkDriver@cassandra:52708/user/MapOutputTracker
14/11/25 23:39:06 INFO AkkaUtils: Connecting to BlockManagerMaster: akka.tcp://sparkDriver@cassandra:52708/user/BlockManagerMaster
14/11/25 23:39:06 INFO DiskBlockManager: Created local directory at /tmp/spark-local-20141125233906-4de2
14/11/25 23:39:06 INFO MemoryStore: MemoryStore started with capacity 267.3 MB
14/11/25 23:39:07 INFO NettyBlockTransferService: Server created on 43710
14/11/25 23:39:07 INFO BlockManagerMaster: Trying to register BlockManager
14/11/25 23:39:07 INFO BlockManagerMaster: Registered BlockManager
14/11/25 23:39:07 INFO AkkaUtils: Connecting to HeartbeatReceiver: akka.tcp://sparkDriver@cassandra:52708/user/HeartbeatReceiver
14/11/25 23:40:06 INFO CoarseGrainedExecutorBackend: Got assigned task 1
14/11/25 23:40:06 INFO Executor: Running task 0.0 in stage 0.0 (TID 1)
14/11/25 23:40:06 INFO Executor: Fetching http://192.168.206.134:54343/jars/spark-cassandra-connector-assembly-1.1.0-SNAPSHOT.jar with timestamp 1416955139048
14/11/25 23:40:06 INFO Utils: Fetching http://192.168.206.134:54343/jars/spark-cassandra-connector-assembly-1.1.0-SNAPSHOT.jar to /tmp/fetchFileTemp6750709298488214227.tmp
14/11/25 23:40:06 INFO Executor: Adding file:/home/cassandra/spark/work/app-20141125233859-0001/1/./spark-cassandra-connector-assembly-1.1.0-SNAPSHOT.jar to class loader
14/11/25 23:40:06 INFO TorrentBroadcast: Started reading broadcast variable 0
14/11/25 23:40:07 INFO MemoryStore: ensureFreeSpace(3082) called with curMem=0, maxMem=280248975
14/11/25 23:40:07 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 3.0 KB, free 267.3 MB)
14/11/25 23:40:07 INFO BlockManagerMaster: Updated info of block broadcast_0_piece0
14/11/25 23:40:07 INFO TorrentBroadcast: Reading broadcast variable 0 took 696 ms
14/11/25 23:40:07 INFO MemoryStore: ensureFreeSpace(4496) called with curMem=3082, maxMem=280248975
14/11/25 23:40:07 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 4.4 KB, free 267.3 MB)
14/11/25 23:40:08 INFO CassandraConnector: Connected to Cassandra cluster: Caspark
14/11/25 23:40:08 INFO Cluster: New Cassandra host /192.168.206.135:9042 added
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.135 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.135 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.135 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.135 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.134 (datacenter1)
14/11/25 23:40:08 INFO Cluster: New Cassandra host cassandra/192.168.206.134:9042 added
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.134 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.134 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.135 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.134 (datacenter1)
14/11/25 23:40:08 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 192.168.206.134 (datacenter1)
14/11/25 23:40:10 INFO Executor: Finished task 0.0 in stage 0.0 (TID 1). 1244 bytes result sent to driver
14/11/25 23:40:10 INFO CassandraConnector: Disconnected from Cassandra cluster: Caspark
14/11/25 23:40:28 INFO CoarseGrainedExecutorBackend: Got assigned task 3
14/11/25 23:40:28 INFO Executor: Running task 0.0 in stage 1.0 (TID 3)
14/11/25 23:40:28 INFO TorrentBroadcast: Started reading broadcast variable 1
14/11/25 23:40:28 INFO MemoryStore: ensureFreeSpace(3431) called with curMem=7578, maxMem=280248975
14/11/25 23:40:28 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 3.4 KB, free 267.3 MB)
14/11/25 23:40:28 INFO BlockManagerMaster: Updated info of block broadcast_1_piece0
14/11/25 23:40:28 INFO TorrentBroadcast: Reading broadcast variable 1 took 23 ms
14/11/25 23:40:28 INFO MemoryStore: ensureFreeSpace(5032) called with curMem=11009, maxMem=280248975
14/11/25 23:40:28 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 4.9 KB, free 267.3 MB)
14/11/25 23:40:28 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 3)
java.lang.ClassNotFoundException: $line28.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$anonfun$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:59)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:57)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
14/11/25 23:40:28 INFO CoarseGrainedExecutorBackend: Got assigned task 5
14/11/25 23:40:28 INFO Executor: Running task 0.1 in stage 1.0 (TID 5)
14/11/25 23:40:28 ERROR Executor: Exception in task 0.1 in stage 1.0 (TID 5)
java.lang.ClassNotFoundException: $line28.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$anonfun$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:59)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:57)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
14/11/25 23:40:28 INFO CoarseGrainedExecutorBackend: Got assigned task 7
14/11/25 23:40:28 INFO Executor: Running task 0.2 in stage 1.0 (TID 7)
14/11/25 23:40:28 ERROR Executor: Exception in task 0.2 in stage 1.0 (TID 7)
java.lang.ClassNotFoundException: $line28.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$anonfun$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:59)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:57)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
14/11/25 23:40:28 INFO CoarseGrainedExecutorBackend: Got assigned task 9
14/11/25 23:40:28 INFO Executor: Running task 0.3 in stage 1.0 (TID 9)
14/11/25 23:40:28 INFO Executor: Executor is trying to kill task 0.3 in stage 1.0 (TID 9)
14/11/25 23:40:28 ERROR Executor: Exception in task 0.3 in stage 1.0 (TID 9)
org.apache.spark.TaskKilledException
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

If this is still an issue, please raise it on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
