### ISSUE TITLE
Random exception spark 1.1.0 + cassandra driver 1.1.0

### ISSUE THREAD

**Issue by lvicentesanchez** [datastax/spark-cassandra-connector#483]
I'm getting this random exception and will try to provide as much information as possible but I don't really understand what the problem is.

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 12.0 failed 1 times, most recent failure: Lost task 0.0 in stage 12.0 (TID 108, localhost): java.lang.InstantiationException:
        sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        com.datastax.spark.connector.rdd.reader.AnyObjectFactory.newInstance(AnyObjectFactory.scala:107)
        com.datastax.spark.connector.rdd.reader.ClassBasedRowReader.read(ClassBasedRowReader.scala:118)
        com.datastax.spark.connector.rdd.reader.KeyValueRowReader.read(KeyValueRowReader.scala:30)
        com.datastax.spark.connector.rdd.reader.KeyValueRowReader.read(KeyValueRowReader.scala:19)
        com.datastax.spark.connector.rdd.CassandraRDD$$anonfun$12.apply(CassandraRDD.scala:344)
        com.datastax.spark.connector.rdd.CassandraRDD$$anonfun$12.apply(CassandraRDD.scala:344)
        scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        scala.collection.Iterator$$anon$13.next(Iterator.scala:372)
        com.datastax.spark.connector.util.CountingIterator.next(CountingIterator.scala:13)
        scala.collection.Iterator$class.foreach(Iterator.scala:727)
        com.datastax.spark.connector.util.CountingIterator.foreach(CountingIterator.scala:4)
        org.apache.spark.shuffle.hash.HashShuffleWriter.write(HashShuffleWriter.scala:65)
        org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        java.lang.Thread.run(Thread.java:745)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1185)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1174)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1173)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1173)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:688)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:688)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1391)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I'm using java8 on my test environment.

The column family has been created with this cql script,

```
CREATE TABLE users (
  game TEXT,
  time TIMESTAMP,
  counter BLOB,
  PRIMARY KEY (game, time)
) WITH DEFAULT_TIME_TO_LIVE = 2678400;
```

The key of my cassandra table is mapped to a case class,

```
case class Key(game: String, time: Long)
```

and the content is a serialised ByteBuffer. The RowReader looks like this,

```
  implicit val counterRowReader = new RowReader[(Key, ByteBuffer)] with ThisRowReaderAsFactory[(Key, ByteBuffer)] {
    override def read(row: Row, columns: Array[String], protocol: ProtocolVersion): (Key, ByteBuffer) =
      (Key(row.getString(Columns.Game), row.getDate(Columns.Time).getTime), row.getBytes(Columns.Counter))

    override val columnNames: Option[Seq[String]] =
      some(Columns.All.map(_.name))

    override val requiredColumns: Option[Int] =
      columnNames.map(_.size)

    override val targetClass: Class[(Key, ByteBuffer)] =
      classOf[(Key, ByteBuffer)]
  }
```

The data is written back to cassandra using this case class,

```
case class Users(game: String, time: Long, counter: Array[Byte])
```

If I start the streaming job when table is empty I don't get too many exception; but if it's not empty, I get more.

Even if there are exceptions, the data stored in cassandra seems to be OK and matches the expected values so... I'm a bit confused.

**Comment by lvicentesanchez** [comment]
Sorry, I have been out on holidays and I have just seen this. I will try to create a minimal example that reproduces the issue.

**Comment by bcantoni** [comment]
If this problem is still reproducible, could you raise it on the users' mailing list? (We are going to close down the GitHub Issues section.)

https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
