### ISSUE TITLE
ClassCastException when doing reduceByKey

### ISSUE THREAD

**Issue by jelgh** [datastax/spark-cassandra-connector#492]
Hello,

I'm getting a weird ClassCastException when trying to run a Spark job that reads data from Cassandra (using spark-cassandra-connector).

It happens when it does a reduceByKey on a `JavaPairRDD<String, MyClass>` (as can be seen on the second line in the log output).

I've Googled a lot for it but cannot find anything; you guys have any idea what it could be? 

## Set up
Running a Spark Cluster with DSE 4.5 (`Spark 0.9.1`) and this is the dependencies in the Java Driver:
```
<dependency>
    <groupId>com.datastax.cassandra</groupId>
    <artifactId>cassandra-driver-core</artifactId>
    <version>2.0.4</version>
</dependency>
<dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-core_2.10</artifactId>
    <version>0.9.1</version>
</dependency>
<dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-streaming_2.10</artifactId>
    <version>0.9.1</version>
</dependency>
<dependency>
    <groupId>com.datastax.spark</groupId>
    <artifactId>spark-cassandra-connector-java_2.10</artifactId>
    <version>1.0.0</version>
</dependency>
```
I've tried with version `1.0.0`, `1.0.1` and `1.0.2` of `spark-cassandra-connector-java_2.10`.

## Log output from driver
```
INFO  [2014-12-19 09:58:50,818] org.apache.spark.scheduler.TaskSetManager: Starting task 2.0:0 as TID 0 on executor 2: x.y.z.51 (NODE_LOCAL)
INFO  [2014-12-19 09:58:53,756] org.apache.spark.scheduler.DAGScheduler: Submitting 5 missing tasks from Stage 3 (MapPartitionsRDD[9] at reduceByKey at MyClassSparkWorker.java:103)
INFO  [2014-12-19 09:58:53,757] org.apache.spark.scheduler.TaskSchedulerImpl: Adding task set 3.0 with 5 tasks
INFO  [2014-12-19 09:58:53,773] org.apache.spark.scheduler.TaskSetManager: Serialized task 2.0:0 as 6789279 bytes in 2953 ms
INFO  [2014-12-19 09:58:53,776] org.apache.spark.scheduler.TaskSetManager: Starting task 2.0:2 as TID 1 on executor 1: x.y.z.52 (NODE_LOCAL)
INFO  [2014-12-19 09:58:53,789] org.apache.spark.scheduler.TaskSetManager: Serialized task 2.0:2 as 6789277 bytes in 12 ms
INFO  [2014-12-19 09:58:53,789] org.apache.spark.scheduler.TaskSetManager: Starting task 2.0:1 as TID 2 on executor 0: x.y.z.55 (NODE_LOCAL)
INFO  [2014-12-19 09:58:53,805] org.apache.spark.scheduler.TaskSetManager: Serialized task 2.0:1 as 6789279 bytes in 16 ms
INFO  [2014-12-19 09:58:53,806] org.apache.spark.scheduler.TaskSetManager: Starting task 2.0:4 as TID 3 on executor 3: x.y.z.54 (NODE_LOCAL)
INFO  [2014-12-19 09:58:53,846] org.apache.spark.scheduler.TaskSetManager: Serialized task 2.0:4 as 6789278 bytes in 40 ms
INFO  [2014-12-19 09:58:53,847] org.apache.spark.scheduler.TaskSetManager: Starting task 2.0:3 as TID 4 on executor 1: x.y.z.52 (NODE_LOCAL)
INFO  [2014-12-19 09:58:53,858] org.apache.spark.scheduler.TaskSetManager: Serialized task 2.0:3 as 6789281 bytes in 10 ms
INFO  [2014-12-19 09:58:53,861] org.apache.spark.scheduler.TaskSetManager: Starting task 3.0:0 as TID 5 on executor 2: x.y.z.51 (NODE_LOCAL)
INFO  [2014-12-19 09:58:53,886] org.apache.spark.scheduler.TaskSetManager: Serialized task 3.0:0 as 6789278 bytes in 24 ms
INFO  [2014-12-19 09:58:53,886] org.apache.spark.scheduler.TaskSetManager: Starting task 3.0:2 as TID 6 on executor 1: x.y.z.52 (NODE_LOCAL)
INFO  [2014-12-19 09:58:54,902] org.apache.spark.scheduler.TaskSetManager: Serialized task 3.0:2 as 6789276 bytes in 1015 ms
INFO  [2014-12-19 09:58:54,903] org.apache.spark.scheduler.TaskSetManager: Starting task 3.0:1 as TID 7 on executor 0: x.y.z.55 (NODE_LOCAL)
INFO  [2014-12-19 09:58:55,003] org.apache.spark.scheduler.TaskSetManager: Serialized task 3.0:1 as 6789278 bytes in 100 ms
INFO  [2014-12-19 09:58:55,004] org.apache.spark.scheduler.TaskSetManager: Starting task 3.0:4 as TID 8 on executor 3: x.y.z.54 (NODE_LOCAL)
INFO  [2014-12-19 09:58:55,033] org.apache.spark.scheduler.TaskSetManager: Serialized task 3.0:4 as 6789277 bytes in 28 ms
INFO  [2014-12-19 09:58:55,033] org.apache.spark.scheduler.TaskSetManager: Starting task 3.0:3 as TID 9 on executor 1: x.y.z.52 (NODE_LOCAL)
INFO  [2014-12-19 09:58:55,097] org.apache.spark.scheduler.TaskSetManager: Serialized task 3.0:3 as 6789280 bytes in 63 ms
WARN  [2014-12-19 09:58:57,705] org.apache.spark.scheduler.TaskSetManager: Lost TID 0 (task 2.0:0)
WARN  [2014-12-19 09:58:57,713] org.apache.spark.scheduler.TaskSetManager: Loss was due to java.lang.ClassCastException
java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field com.datastax.spark.connector.rdd.reader.ClassBasedRowReader.setterConverters of type scala.collection.immutable.Map in instance of com.datastax.spark.connector.rdd.reader.ClassBasedRowReader
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:40)
	at org.apache.spark.scheduler.ShuffleMapTask$.deserializeInfo(ShuffleMapTask.scala:69)
	at org.apache.spark.scheduler.ShuffleMapTask.readExternal(ShuffleMapTask.scala:138)
	at java.io.ObjectInputStream.readExternalData(ObjectInputStream.java:1837)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1796)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:40)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:62)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$run$1.apply$mcV$sp(Executor.scala:193)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsUser(SparkHadoopUtil.scala:45)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jelgh** [comment]
@pkolaczk the JIRA issue: https://datastax-oss.atlassian.net/browse/SPARKC-16

**Comment by pkolaczk** [comment]
Thank you. We'll take a look.

[image: datastax_logo.png] <http://www.datastax.com/>

PIOTR KOŁACZKOWSKI

Lead Software Engineer, DSE Analytics | pkolaczk@datastax.com

[image: twitter] <https://twitter.com/pkolaczk> [image: facebook.png]
<https://www.facebook.com/datastax> [image: linkedin]
<https://www.linkedin.com/in/pkolaczk> [image: g+.png]
<https://plus.google.com/+Datastax/about>
<http://feeds.feedburner.com/datastax> <https://github.com/datastax/>

2015-01-05 9:41 GMT+01:00 Johannes Elgh <notifications@github.com>:
