### ISSUE TITLE
Failed to open thrift connection to Cassandra

### ISSUE THREAD

**Issue by javierTQ** [datastax/spark-cassandra-connector#493]
The versions that i use -->  Spark 1.1.1, Cassandra 2.1.2, spark-cassandra-connector 1.1.0 and jdk8_25.

I have been using the connector some weeks. I create some spark application to write in cassandra without any problem, but now i'm working in a spark application to read the data that i stored in cassandra and a strange exception is thrown.

Below you can see the code of my spark application and a part of the output by the eclipse console. I run the application in local where i have installed the last version of DatastaxCommunityEdition (2.1.2). Also i tested in a ubuntu server where i have installed spark (cassandra is installed in a second server).

Code:

SparkConf conf = new SparkConf();
conf.setAppName("MergeGeoLocation");

conf.setMaster("local[4]");
conf.set("spark.cassandra.connection.host", "127.0.0.1");
conf.set("spark.cassandra.connection.native.port", "9042");
conf.set("spark.cassandra.connection.rpc.port", "9160");

SparkContext context = new SparkContext(conf);
SparkContextJavaFunctions functions = CassandraJavaUtil.javaFunctions(context);	
CassandraJavaRDD<CassandraRow> rdd = functions.cassandraTable("aisp", "host_sample");
rdd.cache();
rdd.foreach(row -> System.out.println(row.toString()));

Output:
...
14/12/19 11:19:53 INFO core.Cluster: New Cassandra host /127.0.0.1:9042 added
14/12/19 11:19:53 INFO cql.CassandraConnector: Connected to Cassandra cluster: Test Cluster
14/12/19 11:19:53 INFO cql.LocalNodeFirstLoadBalancingPolicy: Adding host 127.0.0.1 (datacenter1)
14/12/19 11:19:53 INFO cql.LocalNodeFirstLoadBalancingPolicy: Adding host 127.0.0.1 (datacenter1)
Exception in thread "main" java.io.IOException: Failed to open thrift connection to Cassandra at 127.0.0.1:9160
	at com.datastax.spark.connector.cql.CassandraConnector.createThriftClient(CassandraConnector.scala:132)
	at com.datastax.spark.connector.cql.CassandraConnector.createThriftClient(CassandraConnector.scala:138)
	at com.datastax.spark.connector.cql.CassandraConnector.withCassandraClientDo(CassandraConnector.scala:144)
	at com.datastax.spark.connector.rdd.partitioner.CassandraRDDPartitioner.partitions(CassandraRDDPartitioner.scala:158)
	at com.datastax.spark.connector.rdd.CassandraRDD.getPartitions(CassandraRDD.scala:294)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:204)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:202)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:202)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1157)
	at org.apache.spark.rdd.RDD.foreach(RDD.scala:759)
	at org.apache.spark.api.java.JavaRDDLike$class.foreach(JavaRDDLike.scala:298)
	at org.apache.spark.api.java.JavaRDD.foreach(JavaRDD.scala:32)
	at apps.MergeGeoLocation.main(MergeGeoLocation.java:51)
Caused by: java.lang.NoSuchMethodError: org.apache.cassandra.thrift.TFramedTransportFactory.openTransport(Ljava/lang/String;I)Lorg/apache/thrift/transport/TTransport;
	at com.datastax.spark.connector.cql.DefaultConnectionFactory$.createThriftClient(CassandraConnectionFactory.scala:47)
	at com.datastax.spark.connector.cql.CassandraConnector.createThriftClient(CassandraConnector.scala:127)
	... 13 more
14/12/19 11:19:54 INFO cql.CassandraConnector: Disconnected from Cassandra cluster: Test Cluster

Someone can help me?

Thanks :-)

**Comment by javierTQ** [comment]
Adding the next dependency to the pom fix the problem:

<dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-all</artifactId>
            <version>2.1.2</version>
</dependency>

Thanks for your help :-).
