### ISSUE TITLE
Failing to connect with Cassandra on Docker

### ISSUE THREAD

**Issue by tadanki** [datastax/spark-cassandra-connector#507]
I am running a Cassandra DSE on docker and am able to run tests from my projects that connect to it and load/read data. I can also connect to my instance via the **cqlsh**. 

However, my spark connector refuses to connect with the cassandra node on docker with the following: 

```javascript
  Cause: java.lang.IllegalArgumentException: Contact points contain multiple data centers:
  at com.datastax.spark.connector.cql.LocalNodeFirstLoadBalancingPolicy.init(LocalNodeFirstLoadBalancingPolicy.scala:41)
  at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1024)
  at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:270)
  at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:167)
```

I am currently forwarding the ports from the host to the docker container, and as i mentioned earlier, I am able to run other tests against this instance, just not through spark. 

Any pointers ?

Many Thanks,
Karthik

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector User's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
