### ISSUE TITLE
sbt assembly 

### ISSUE THREAD

**Issue by kolobok01** [datastax/spark-cassandra-connector#515]
```
.ivy2/cache/org.eclipse.jetty.orbit/javax.activation/orbits/javax.activation-1.1.0.v201105071233.jar:META-INF/ECLIPSEF.RSA
	at sbtassembly.Plugin$Assembly$.sbtassembly$Plugin$Assembly$$applyStrategy$1(Plugin.scala:253)
	at sbtassembly.Plugin$Assembly$$anonfun$15.apply(Plugin.scala:270)
	at sbtassembly.Plugin$Assembly$$anonfun$15.apply(Plugin.scala:267)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbtassembly.Plugin$Assembly$.applyStrategies(Plugin.scala:272)
	at sbtassembly.Plugin$Assembly$.x$4$lzycompute$1(Plugin.scala:172)
	at sbtassembly.Plugin$Assembly$.x$4$1(Plugin.scala:170)
	at sbtassembly.Plugin$Assembly$.stratMapping$lzycompute$1(Plugin.scala:170)
	at sbtassembly.Plugin$Assembly$.stratMapping$1(Plugin.scala:170)
	at sbtassembly.Plugin$Assembly$.inputs$lzycompute$1(Plugin.scala:214)
	at sbtassembly.Plugin$Assembly$.inputs$1(Plugin.scala:204)
	at sbtassembly.Plugin$Assembly$.apply(Plugin.scala:230)
	at sbtassembly.Plugin$Assembly$$anonfun$assemblyTask$1.apply(Plugin.scala:373)
	at sbtassembly.Plugin$Assembly$$anonfun$assemblyTask$1.apply(Plugin.scala:370)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (kafka-streaming/*:assembly) deduplicate: different file contents found in the following:
[error] /Users/o606918/.ivy2/cache/org.eclipse.jetty.orbit/javax.transaction/orbits/javax.transaction-1.1.1.v201105210645.jar:META-INF/ECLIPSEF.RSA
[error] /Users/o606918/.ivy2/cache/org.eclipse.jetty.orbit/javax.servlet/orbits/javax.servlet-3.0.0.v201112011016.jar:META-INF/ECLIPSEF.RSA
[error] /Users/o606918/.ivy2/cache/org.eclipse.jetty.orbit/javax.mail.glassfish/orbits/javax.mail.glassfish-1.4.1.v201005082020.jar:META-INF/ECLIPSEF.RSA
[error] /Users/o606918/.ivy2/cache/org.eclipse.jetty.orbit/javax.activation/orbits/javax.activation-1.1.0.v201105071233.jar:META-INF/ECLIPSEF.RSA

````
I have tried different merging case classes with no luck 
```
   mergeStrategy in assembly <<= (mergeStrategy in assembly) {
      (old) => {
        case PathList("com", "google", xs @ _*) => MergeStrategy.last
        case PathList("META-INF", "ECLIPSEF.RSA") => MergeStrategy.first
        case x if x.startsWith("META-INF/mailcap") => MergeStrategy.last
        case x if x.startsWith("pom.properties") => MergeStrategy.last
        case x => old(x)
      }
    }
```
Any help would be greatly appreciated

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
