### ISSUE TITLE
NoSuchMethodError: com.datastax.spark.connector.japi.CassandraJavaUtil.mapToRow

### ISSUE THREAD

**Issue by msolima** [datastax/spark-cassandra-connector#517]
Hello,
I'm starting with spark and cassandra, I managed to run simple spark jobs from shell and using spark-submit.
Now am trying to use the connector to connect to cassandra.

MY spark version is 1.2.0 and my cassandra version is 2.1.2

Here's the Java Code that am using ( I used the JavaApiDemo) sample. I didn't change much in the sample code provided in the repository of the datastax spark cassandra connector.
```
import com.datastax.spark.connector.japi.CassandraRow;
import com.google.common.base.Objects;
import org.apache.hadoop.util.StringUtils;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.function.Function;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import static com.datastax.spark.connector.japi.CassandraJavaUtil.javaFunctions;
import static com.datastax.spark.connector.japi.CassandraJavaUtil.mapRowTo;
import static com.datastax.spark.connector.japi.CassandraJavaUtil.mapToRow;

public class JavaApiDemo implements Serializable {

    public JavaApiDemo() {
        // just an initialisation of Spark Context
        SparkConf conf = new SparkConf().setAppName("JavaConnector TestTT").setMaster("spark://135.121.21.179:7077");
        conf.set("spark.cassandra.connection.host", "135.121.21.195");
        JavaSparkContext sc = new JavaSparkContext(conf);

        // here we are going to save some data to Cassandra...
        List<Person> people = Arrays.asList(
                Person.newInstance(1, "John", new Date()),
                Person.newInstance(2, "Anna", new Date()),
                Person.newInstance(3, "Andrew", new Date())
        );
        JavaRDD<Person> rdd = sc.parallelize(people);
        javaFunctions(rdd)
                .writerBuilder("test", "people", mapToRow(Person.class))
                .saveToCassandra();

        // use case: we want to read that data as an RDD of CassandraRows and convert them to strings...
        JavaRDD<String> cassandraRowsRDD = javaFunctions(sc).cassandraTable("test", "people")
                .map(new Function<CassandraRow, String>() {
                    public String call(CassandraRow cassandraRow) throws Exception {
                        return cassandraRow.toString();
                    }
                });
        System.out.println("Data as CassandraRows: \n" + StringUtils.join("\n", cassandraRowsRDD.collect()));
        sc.stop();
    }

    public static void main(String[] args) {
        new JavaApiDemo();
    }

    public static class Person implements Serializable {
        private Integer id;
        private String name;
        private Date birthDate;

        public static Person newInstance(Integer id, String name, Date birthDate) {
            Person person = new Person();
            person.setId(id);
            person.setName(name);
            person.setBirthDate(birthDate);
            return person;
        }

        public Integer getId() {
            return id;
        }

        public void setId(Integer id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Date getBirthDate() {
            return birthDate;
        }

        public void setBirthDate(Date birthDate) {
            this.birthDate = birthDate;
        }

        @Override
        public String toString() {
            return Objects.toStringHelper(this)
                    .add("id", id)
                    .add("name", name)
                    .add("birthDate", birthDate)
                    .toString();
        }
    }
}
```
and here is the pom.xml file 
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>moataz_cassandra_connector</groupId>
  <artifactId>1.0.0</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency> <!-- Spark dependency -->
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_2.10</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.datastax.spark</groupId>
      <artifactId>spark-cassandra-connector_2.10</artifactId>
      <version>1.2.0-alpha1</version>
    </dependency>
    <dependency>
      <groupId>com.datastax.spark</groupId>
      <artifactId>spark-cassandra-connector-java_2.10</artifactId>
      <version>1.2.0-alpha1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-streaming_2.10</artifactId>
      <version>1.2.0</version>
    </dependency>
  </dependencies>
</project>
```

Then I removed the lines that were causing the issue         
```
JavaRDD<Person> rdd = sc.parallelize(people);
        javaFunctions(rdd)
                .writerBuilder("test", "people", mapToRow(Person.class))
                .saveToCassandra();
```
So I was only trying to read from the table from cassandra , then I got the following stack trace error which is driving me crazy 

```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/01/19 15:34:38 INFO SecurityManager: Changing view acls to: root
15/01/19 15:34:38 INFO SecurityManager: Changing modify acls to: root
15/01/19 15:34:38 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
15/01/19 15:34:39 INFO Slf4jLogger: Slf4jLogger started
15/01/19 15:34:39 INFO Remoting: Starting remoting
15/01/19 15:34:39 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@samdev43:11306]
15/01/19 15:34:39 INFO Utils: Successfully started service 'sparkDriver' on port 11306.
15/01/19 15:34:39 INFO SparkEnv: Registering MapOutputTracker
15/01/19 15:34:39 INFO SparkEnv: Registering BlockManagerMaster
15/01/19 15:34:39 INFO DiskBlockManager: Created local directory at /tmp/spark-local-20150119153439-c16b
15/01/19 15:34:39 INFO MemoryStore: MemoryStore started with capacity 2.8 GB
15/01/19 15:34:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/01/19 15:34:39 INFO HttpFileServer: HTTP File server directory is /tmp/spark-601330cb-a82f-4755-b905-c7358d764f4c
15/01/19 15:34:39 INFO HttpServer: Starting HTTP Server
15/01/19 15:34:39 INFO Utils: Successfully started service 'HTTP file server' on port 38987.
15/01/19 15:34:40 INFO Utils: Successfully started service 'SparkUI' on port 4040.
15/01/19 15:34:40 INFO SparkUI: Started SparkUI at http://samdev43:4040
15/01/19 15:34:40 INFO AppClient$ClientActor: Connecting to master spark://135.121.21.179:7077...
15/01/19 15:34:40 INFO SparkDeploySchedulerBackend: Connected to Spark cluster with app ID app-20150119153440-0026
15/01/19 15:34:40 INFO AppClient$ClientActor: Executor added: app-20150119153440-0026/0 on worker-20150119094259-135.121.21.179-36916 (135.121.21.179:36916) with 2 cores
15/01/19 15:34:40 INFO SparkDeploySchedulerBackend: Granted executor ID app-20150119153440-0026/0 on hostPort 135.121.21.179:36916 with 2 cores, 512.0 MB RAM
15/01/19 15:34:40 INFO AppClient$ClientActor: Executor updated: app-20150119153440-0026/0 is now LOADING
15/01/19 15:34:40 INFO AppClient$ClientActor: Executor updated: app-20150119153440-0026/0 is now RUNNING
15/01/19 15:34:40 INFO NettyBlockTransferService: Server created on 15055
15/01/19 15:34:40 INFO BlockManagerMaster: Trying to register BlockManager
15/01/19 15:34:40 INFO BlockManagerMasterActor: Registering block manager samdev43:15055 with 2.8 GB RAM, BlockManagerId(<driver>, samdev43, 15055)
15/01/19 15:34:40 INFO BlockManagerMaster: Registered BlockManager
15/01/19 15:34:40 INFO SparkDeploySchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
15/01/19 15:34:40 INFO Cluster: New Cassandra host /135.121.21.195:9042 added
15/01/19 15:34:40 INFO Cluster: New Cassandra host /135.121.21.196:9042 added
15/01/19 15:34:40 INFO CassandraConnector: Connected to Cassandra cluster: 5620sam_AuxiliaryDB
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.196 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.195 (datacenter1)
15/01/19 15:34:40 INFO Cluster: New Cassandra host /135.121.21.197:9042 added
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.197 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.195 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.195 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.197 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.196 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.196 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.195 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.196 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.197 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.195 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.196 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.197 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.197 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.195 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.196 (datacenter1)
15/01/19 15:34:40 INFO LocalNodeFirstLoadBalancingPolicy: Adding host 135.121.21.197 (datacenter1)
15/01/19 15:34:41 INFO SparkContext: Starting job: collect at JavaApiDemo.java:42
15/01/19 15:34:41 INFO DAGScheduler: Got job 0 (collect at JavaApiDemo.java:42) with 3 output partitions (allowLocal=false)
15/01/19 15:34:41 INFO DAGScheduler: Final stage: Stage 0(collect at JavaApiDemo.java:42)
15/01/19 15:34:41 INFO DAGScheduler: Parents of final stage: List()
15/01/19 15:34:41 INFO DAGScheduler: Missing parents: List()
15/01/19 15:34:41 INFO DAGScheduler: Submitting Stage 0 (MappedRDD[1] at map at JavaApiDemo.java:37), which has no missing parents
15/01/19 15:34:41 INFO MemoryStore: ensureFreeSpace(5656) called with curMem=0, maxMem=3021975060
15/01/19 15:34:41 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 5.5 KB, free 2.8 GB)
15/01/19 15:34:41 INFO CassandraConnector: Disconnected from Cassandra cluster: 5620sam_AuxiliaryDB
15/01/19 15:34:41 INFO MemoryStore: ensureFreeSpace(3855) called with curMem=5656, maxMem=3021975060
15/01/19 15:34:41 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 3.8 KB, free 2.8 GB)
15/01/19 15:34:41 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on samdev43:15055 (size: 3.8 KB, free: 2.8 GB)
15/01/19 15:34:41 INFO BlockManagerMaster: Updated info of block broadcast_0_piece0
15/01/19 15:34:41 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:838
15/01/19 15:34:41 INFO DAGScheduler: Submitting 3 missing tasks from Stage 0 (MappedRDD[1] at map at JavaApiDemo.java:37)
15/01/19 15:34:41 INFO TaskSchedulerImpl: Adding task set 0.0 with 3 tasks
15/01/19 15:34:44 INFO SparkDeploySchedulerBackend: Registered executor: Actor[akka.tcp://sparkExecutor@135.121.21.179:58351/user/Executor#-1591918270] with ID 0
15/01/19 15:34:44 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, 135.121.21.179, ANY, 2112 bytes)
15/01/19 15:34:44 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, 135.121.21.179, ANY, 2146 bytes)
15/01/19 15:34:45 INFO BlockManagerMasterActor: Registering block manager 135.121.21.179:54937 with 265.4 MB RAM, BlockManagerId(0, 135.121.21.179, 54937)
15/01/19 15:34:45 INFO TaskSetManager: Starting task 2.0 in stage 0.0 (TID 2, 135.121.21.179, ANY, 2111 bytes)
15/01/19 15:34:45 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1, 135.121.21.179): java.lang.ClassNotFoundException: com.datastax.spark.connector.rdd.partitioner.CassandraPartition
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:59)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

15/01/19 15:34:45 INFO TaskSetManager: Starting task 1.1 in stage 0.0 (TID 3, 135.121.21.179, ANY, 2146 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 1]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 4, 135.121.21.179, ANY, 2112 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 2.0 in stage 0.0 (TID 2) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 2]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 2.1 in stage 0.0 (TID 5, 135.121.21.179, ANY, 2111 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 1.1 in stage 0.0 (TID 3) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 3]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 1.2 in stage 0.0 (TID 6, 135.121.21.179, ANY, 2146 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 4) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 4]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 7, 135.121.21.179, ANY, 2112 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 2.1 in stage 0.0 (TID 5) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 5]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 2.2 in stage 0.0 (TID 8, 135.121.21.179, ANY, 2111 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 7) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 6]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 9, 135.121.21.179, ANY, 2112 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 1.2 in stage 0.0 (TID 6) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 7]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 1.3 in stage 0.0 (TID 10, 135.121.21.179, ANY, 2146 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 2.2 in stage 0.0 (TID 8) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 8]
15/01/19 15:34:45 INFO TaskSetManager: Starting task 2.3 in stage 0.0 (TID 11, 135.121.21.179, ANY, 2111 bytes)
15/01/19 15:34:45 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 9) on executor 135.121.21.179: java.lang.ClassNotFoundException (com.datastax.spark.connector.rdd.partitioner.CassandraPartition) [duplicate 9]
15/01/19 15:34:45 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
15/01/19 15:34:45 INFO TaskSchedulerImpl: Cancelling stage 0
15/01/19 15:34:45 INFO TaskSchedulerImpl: Stage 0 was cancelled
15/01/19 15:34:45 INFO DAGScheduler: Job 0 failed: collect at JavaApiDemo.java:42, took 4.485585 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 9, 135.121.21.179): java.lang.ClassNotFoundException: com.datastax.spark.connector.rdd.partitioner.CassandraPartition
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:59)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1420)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor.aroundReceive(DAGScheduler.scala:1375)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by msolima** [comment]
Please Help, this is very critical in my project. Thanks alot

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC
