### ISSUE TITLE
Is the cluster topology ever refreshed?

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#523]
Hi,

We have a set of Spark Streaming jobs consuming data from Kafka and writing it to Cassandra.

We had to grow the cluster of a prod platform by doubling the number of Cassandra nodes. Long story short, something went wrong during that process and one node is failing to properly function. It joined the ring but did not property answered requests so we took it temporarily down by issuing a 
`nodetool disablegossip + disablebinary`

The node, with IP `xx.54` is now gone from the ring as we can observe from the `nodetool status`
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns   Host ID                               Rack
UN  xx.xx.xx.253   81.24 GB   256     22.2%  6354cbc2-379a-4a3c-93f8-bd3cf08449c8  rack1
UN  xx.xx.xx.240  1.11 GB    256     20.0%  d35d244c-00ea-4b27-a447-d7c53d1cea50  rack1
UN  xx.xx.xx.251   101.21 GB  256     19.0%  b3747c51-3066-41f4-a3ef-36a6c8e4a8e8  rack1
UN  xx.xx.xx.189  99.95 GB   256     20.7%  f74a4265-56b7-442a-a7fe-7c36c93e0022  rack1
UN  xx.xx.xx.99    626.44 MB  256     18.0%  cb598192-4690-43d8-9f82-746477dc5db9  rack1
```

Nevertheless, the streaming job is still trying to unsuccessfully contact the node, failing on every iteration. This causes some tasks to fail and the job to lag behind. Spark Streaming is very timing-sensitive.

Here's a trace of one executor trying to connect to this node, that should have been removed from the topology:
```java
15/01/23 15:14:24 ERROR Session: Error creating pool to /xx.xx.xx.54:9042
com.datastax.driver.core.TransportException: [/xx.xx.xx.54:9042] Cannot connect
```

Below you'll find the full trace showing the node being 'discovered' (that's the part I don't get) when the topology being loaded.

Our current connection TTL settting `cassandra.connection.keep_alive_ms` is on 12secs, this traces are from 15-30 minutes after the node has been brought down.

Any ideas what to do as workaround and solution?  Restarting the job is not an option as we will lose the data in the streaming backlog.

Thanks,

Gerard.

Full trace:
```
15/01/23 15:14:22 INFO CassandraConnector: Disconnected from Cassandra cluster: cassandra-streaming
15/01/23 15:14:22 INFO CassandraConnector: Disconnected from Cassandra cluster: cassandra-streaming
15/01/23 15:14:22 INFO CassandraConnector: Disconnected from Cassandra cluster: cassandra-streaming
15/01/23 15:14:24 INFO Cluster: New Cassandra host /xx.xx.xx.99:9042 added
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.99 (datacenter1)
15/01/23 15:14:24 INFO Cluster: New Cassandra host /xx.xx.xx.240:9042 added
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.240 (datacenter1)
15/01/23 15:14:24 INFO Cluster: New Cassandra host /xx.xx.xx.253:9042 added
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.253 (datacenter1)
15/01/23 15:14:24 INFO CassandraConnector: Connected to Cassandra cluster: cassandra-streaming
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.99 (datacenter1)
15/01/23 15:14:24 INFO Cluster: New Cassandra host /xx.xx.xx.54:9042 added
15/01/23 15:14:24 INFO Cluster: New Cassandra host /xx.xx.xx.251:9042 added
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.251 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.251 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.54 (datacenter1)
15/01/23 15:14:24 INFO Cluster: New Cassandra host /xx.xx.xx.189:9042 added
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.189 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.189 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.99 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.99 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.240 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.240 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.253 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.253 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.54 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.189 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.251 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.240 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.99 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.240 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.253 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.253 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.54 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.189 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.251 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.253 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.54 (datacenter1)
15/01/23 15:14:24 INFO LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.54 (datacenter1)
15/01/23 15:14:24 ERROR Session: Error creating pool to /xx.xx.xx.54:9042
com.datastax.driver.core.TransportException: [/xx.xx.xx.54:9042] Cannot connect
	at com.datastax.driver.core.Connection.<init>(Connection.java:104)
	at com.datastax.driver.core.PooledConnection.<init>(PooledConnection.java:28)
	at com.datastax.driver.core.Connection$Factory.open(Connection.java:458)
	at com.datastax.driver.core.HostConnectionPool.<init>(HostConnectionPool.java:85)
	at com.datastax.driver.core.SessionManager.replacePool(SessionManager.java:239)
	at com.datastax.driver.core.SessionManager.access$400(SessionManager.java:40)
	at com.datastax.driver.core.SessionManager$3.call(SessionManager.java:271)
	at com.datastax.driver.core.SessionManager$3.call(SessionManager.java:263)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused: /xx.xx.xx.54:9042
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	... 3 more
```

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Instead, you can raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC

**Comment by maasg** [comment]
ok
